# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            The DFT Course
tagline:          'By Nathan M. Lui'
description:      'By Nathan M. Lui'
url:              https://thisisntnathan.github.io/
baseurl:          '/dftCourse'

author:
  name:           'Nathan M. Lui'
#  url:            https://thisisntnathan.github.io

plugins:
  - jekyll-gist

sidebar_home_link:  False

include:
    - _pages

google_analytics:   297908426
